### ISSUE TITLE
wrong in cancer_classifier.py

### ISSUE THREAD

**Issue by stutys** [tobegit3hub/tensorflow_template_application#2]
I test run deep_recommend_system-master/cancer_classifier.py, but it reveals that 'module' object has no attribute 'streaming_auc' in line 203. I don't know why, when the tensorflow_examples are running fluently in my PC.
Thanks for your answers.

**Comment by tobegit3hub** [comment]
Can you print your version of TensorFlow? Just try this.

```
python -c "import tensorflow; print(tensorflow.__version__)"
```

**Comment by stutys** [comment]
my TF version: 0.8.0rc0. Is there any problem?

**Comment by tobegit3hub** [comment]
I think this should work with TensorFlow 0.8.0. @stutys 

Can your pull the latest code of this project and run with `python ./cancer_classifier.py`? If there's error please paste the error log here.

**Comment by tobegit3hub** [comment]
0.8.0 is a little out-of-date. It would be better to test with later version.

**Comment by 9vivian88** [comment]
I met the same problem with @stutys

**Comment by stutys** [comment]
Thanks for your answers, the error log is just like this,
`Use the model: wide_and_deep
Use the optimizer: adagrad
Use the model: wide_and_deep
Traceback (most recent call last):
  File "./cancer_classifier.py", line 203, in <module>
    _, auc_op = tf.contrib.metrics.streaming_auc(validate_softmax, new_validate_batch_labels)
AttributeError: 'module' object has no attribute 'streaming_auc'
`
And could you instuct how to update TensorFlow, or i need to install it again with latest version? @tobegit3hub

**Comment by stutys** [comment]
Do you solve the problem? and some solutions? Thanks so much. @9vivian88

**Comment by tobegit3hub** [comment]
Thanks @stutys and @9vivian88 for reporting.

Confirm that it's caused by `tf.contrib.metrics.streaming_auc` which is merged after `r0.9`. You can checkout that file [here](https://github.com/tensorflow/tensorflow/blob/r0.9/tensorflow/contrib/metrics/python/ops/metric_ops.py).

You can upgrade to `0.9+` TensorFlow and `0.11rc` is highly recommended. Or just comment out those lines about `auc` and everything should work again.
